apiVersion: v1
kind: PersistentVolume
metadata:
  name: lmsweb-prd-pv
  namespace: lms
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /path/to/host/directory
